# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "CLI tool for managing multiple Claude Code accounts"
  homepage "https://github.com/caeser1996/claude-switch"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caeser1996/claude-switch/releases/download/v0.7.0/claude-switch_0.7.0_darwin_amd64.tar.gz"
      sha256 "dc82045a688ae305d2671e30e4d5fd3c240c6fe51a8cd6155cb2e74893718833"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caeser1996/claude-switch/releases/download/v0.7.0/claude-switch_0.7.0_darwin_arm64.tar.gz"
      sha256 "e555c01dcde19bac97b22d135adafffb8c0b5ba9c940a922ef374a9c0afa43f5"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v0.7.0/claude-switch_0.7.0_linux_amd64.tar.gz"
      sha256 "f18bc7e4066a47205687d5f6cde38b341341901a79c2c33035f1df651471029d"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v0.7.0/claude-switch_0.7.0_linux_arm64.tar.gz"
      sha256 "17dbec8954885b2a93ae6a7b3a7424a9a0591bba6541cd7f93f84d410cb1d1c5"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  test do
    system "#{bin}/claude-switch", "version"
  end
end
