# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "CLI tool for managing multiple Claude Code accounts"
  homepage "https://github.com/caeser1996/claude-switch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_darwin_amd64.tar.gz"
      sha256 "7d0c9209141446d77ebb17d1f142e3e058adbd09b1349411281d41a726fc69e8"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_darwin_arm64.tar.gz"
      sha256 "b33f380b9f1ff95b33abaf8ecf6c2bf7409e3addfc986cad161ba69d140a2b7a"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_linux_amd64.tar.gz"
      sha256 "b5bb4869d9bf5abd41fcf847fcdbe530c645e00cb49e790acce693750d132c87"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_linux_arm64.tar.gz"
      sha256 "6c820e21eb2c8e35ff82ccfe550429316ae3c2a18e57de555cf99de759e62ed2"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  test do
    system "#{bin}/claude-switch", "version"
  end
end
