# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "CLI tool for managing multiple Claude Code accounts"
  homepage "https://github.com/caeser1996/claude-switch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_darwin_amd64.tar.gz"
      sha256 "20806ef7a068385a99e2684420af2e2a7612bb58919df2e56da5b399d8ed043e"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_darwin_arm64.tar.gz"
      sha256 "a88e28da32d1a453a83c4849a432b5a9772580caeed7f475dc136383ec81dbd6"

      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_linux_amd64.tar.gz"
      sha256 "fcb9b7449c053c6904960f8830604168f311f96a8dfff565a32b7968dba1ad87"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caeser1996/claude-switch/releases/download/v1.0.0/claude-switch_1.0.0_linux_arm64.tar.gz"
      sha256 "0fc5bee25b914e78c2d99bd33c873ae0969f43f58bf50295e6410e3b1acf90cb"
      def install
        bin.install "claude-switch"
        bin.install_symlink "claude-switch" => "cs"
      end
    end
  end

  test do
    system "#{bin}/claude-switch", "version"
  end
end
